# Generated by Django 3.2 on 2024-05-31 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('is_private', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('codename', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='u-1', max_length=12, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authuser.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authuser.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authuser.user'),
        ),
        migrations.CreateModel(
            name='EntityPermissionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authuser.entities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authuser.user')),
            ],
        ),
        migrations.CreateModel(
            name='EntityPermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authuser.entities')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authuser.group')),
            ],
        ),
        migrations.AddField(
            model_name='entities',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authuser.entitytype'),
        ),
        migrations.AddField(
            model_name='entities',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authuser.user'),
        ),
        migrations.AddConstraint(
            model_name='entitypermissionuser',
            constraint=models.UniqueConstraint(fields=('entity', 'user'), name='unique_entity_user'),
        ),
        migrations.AddConstraint(
            model_name='entitypermissiongroup',
            constraint=models.UniqueConstraint(fields=('entity', 'group'), name='unique_entity_group'),
        ),
    ]
