# Generated by Django 3.2 on 2024-07-02 17:58
from django.contrib.auth.hashers import make_password
from django.db import migrations

class Migration(migrations.Migration):
    def insert_default_data(apps, schema_editor):
        # Users
        UserD = apps.get_model('authuser', 'User')
        root_u = UserD.objects.create(
            id=1,
            email='root@algator.com',
            username='root',
            password=make_password('root'),
            is_superuser=True,
            is_active=True,
            uid='u0'
        )
        root_u.save()
        anonymous_u = UserD.objects.create(
            id=2,
            email='anonymous@algator.com',
            username='anonymous',
            password=make_password('anonymous'),
            is_superuser=False,
            is_active=False,
            is_staff=False,
            uid='u1'
        )
        anonymous_u.save()
        algator_u = UserD.objects.create(
            id=3,
            email='algator@algator.com',
            username='algator',
            password=make_password('algator'),
            is_superuser=True,
            is_active=True,
            uid='u2'
        )
        algator_u.save()

        # Custom user
        # User = apps.get_model('authuser', 'User')
        # root_uu = User(id='u0', user=root_u)
        # root_uu.save()
        # anonymous_uu = User(id='u1', user=anonymous_u)
        # anonymous_uu.save()
        # algator_uu = User(id='u2', user=algator_u)
        # algator_uu.save()


        # EntityType
        EntityType = apps.get_model('authuser', 'EntityType')
        system_et = EntityType(id='et0', name='System')
        system_et.save()
        project_et = EntityType(id='et1', name='Project')
        project_et.save()
        algorithm_et = EntityType(id='et2', name='Algorithm')
        algorithm_et.save()
        test_set_et = EntityType(id='et3', name='Test set')
        test_set_et.save()
        groups_et = EntityType(id='et4', name='Groups')
        groups_et.save()
        presenter_et = EntityType(id='et5', name='Presenter')
        presenter_et.save()

        # PermissionType
        PermissionType = apps.get_model('authuser', 'PermissionType')
        can_read_pt = PermissionType(id='p0', name='Can read?', codename='can_read', value=1)
        can_read_pt.save()
        can_write_pt = PermissionType(id='p1', name='Can write?', codename='can_write', value=2)
        can_write_pt.save()
        can_execute_pt = PermissionType(id='p2', name='Can execute?', codename='can_execute', value=4)
        can_execute_pt.save()
        add_project_pt = PermissionType(id='p3', name='Can add project?', codename='can_add_project', value=8)
        add_project_pt.save()
        can_add_testset_pt = PermissionType(id='p4', name='Can add test set?', codename='can_add_testset', value=16)
        can_add_testset_pt.save()
        can_add_algorithm_pt = PermissionType(id='p5', name='Can add algorithm?', codename='can_add_algorithm', value=32)
        can_add_algorithm_pt.save()
        can_edit_rights_pt = PermissionType(id='p6', name='Can edit rights?', codename='can_edit_rights', value=64)
        can_edit_rights_pt.save()
        can_edit_users_pt = PermissionType(id='p7', name='Can edit users?', codename='can_edit_users', value=128)
        can_edit_users_pt.save()
        full_control_pt = PermissionType(id='p1000', name='Full control', codename='full_control', value=0xFFFF)
        full_control_pt.save()

        # Groups
        Group = apps.get_model('authuser', 'Group')
        everyone_g = Group(id='g0', name='everyone', owner=root_u)
        everyone_g.save()
        anonymous_g = Group(id='g1', name='anonymous', owner=root_u)
        anonymous_g.save()

        # Custom groups
        students_group = Group(id='g2', name='students', owner=algator_u)
        students_group.save()


        # Entities
        Entities = apps.get_model('authuser', 'Entities')
        e0 = Entities(id='e0', name='system', entity_type=system_et, is_private=False, owner=root_u)
        e0.save()

        # Entity permission
        Entity_permission = apps.get_model('authuser', 'Entity_permission')
        ep0 = Entity_permission(entity_type=system_et, permission_type=add_project_pt)
        ep0.save()
        ep1 = Entity_permission(entity_type=system_et, permission_type=can_edit_rights_pt)
        ep1.save()
        ep2 = Entity_permission(entity_type=system_et, permission_type=full_control_pt)
        ep2.save()

        ep3 = Entity_permission(entity_type=project_et, permission_type=can_read_pt)
        ep3.save()
        ep4 = Entity_permission(entity_type=project_et, permission_type=can_write_pt)
        ep4.save()
        ep5 = Entity_permission(entity_type=project_et, permission_type=can_execute_pt)
        ep5.save()
        ep6 = Entity_permission(entity_type=project_et, permission_type=can_add_testset_pt)
        ep6.save()
        ep7 = Entity_permission(entity_type=project_et, permission_type=can_add_algorithm_pt)
        ep7.save()
        ep8 = Entity_permission(entity_type=project_et, permission_type=full_control_pt)
        ep8.save()

        ep9 = Entity_permission(entity_type=algorithm_et, permission_type=can_read_pt)
        ep9.save()
        ep10 = Entity_permission(entity_type=algorithm_et, permission_type=can_write_pt)
        ep10.save()
        ep11 = Entity_permission(entity_type=algorithm_et, permission_type=can_execute_pt)
        ep11.save()
        ep12 = Entity_permission(entity_type=algorithm_et, permission_type=full_control_pt)
        ep12.save()

        ep13 = Entity_permission(entity_type=test_set_et, permission_type=can_read_pt)
        ep13.save()
        ep14 = Entity_permission(entity_type=test_set_et, permission_type=can_write_pt)
        ep14.save()
        ep15 = Entity_permission(entity_type=test_set_et, permission_type=full_control_pt)
        ep15.save()

        ep16 = Entity_permission(entity_type=groups_et, permission_type=can_write_pt)
        ep16.save()
        ep17 = Entity_permission(entity_type=groups_et, permission_type=full_control_pt)
        ep17.save()

        ep18 = Entity_permission(entity_type=presenter_et, permission_type=can_read_pt)
        ep18.save()
        ep19 = Entity_permission(entity_type=presenter_et, permission_type=can_write_pt)
        ep19.save()
        ep20 = Entity_permission(entity_type=presenter_et, permission_type=full_control_pt)
        ep20.save()

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_default_data),
    ]
