# Generated by Django 3.2 on 2024-05-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    def insert_default_data(apps, schema_editor):
        # EntityType
        EntityType = apps.get_model('authuser', 'EntityType')
        system_et = EntityType(name='System')
        system_et.save()
        project_et = EntityType(name='Project')
        project_et.save()
        test_set_et = EntityType(name='Test set')
        test_set_et.save()
        algorithm_et = EntityType(name='Algorithm')
        algorithm_et.save()

        # PermissionType
        PermissionType = apps.get_model('authuser', 'PermissionType')
        add_project_pt = PermissionType(name='Can add project?', codename='can_add_project')
        add_project_pt.save()
        add_group_pt = PermissionType(name='Can add group?', codename='can_add_group')
        add_group_pt.save()
        can_read_pt = PermissionType(name='Can read?', codename='can_read')
        can_read_pt.save()
        can_write_pt = PermissionType(name='Can write?', codename='can_write')
        can_write_pt.save()
        can_add_testset_pt = PermissionType(name='Can add test set?', codename='can_add_testset')
        can_add_testset_pt.save()
        can_add_algorithm_pt = PermissionType(name='Can add algorithm?', codename='can_add_algorithm')
        can_add_algorithm_pt.save()

        # Groups
        Group = apps.get_model('authuser', 'Group')
        students_group = Group(name='students')
        students_group.save()

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_default_data),
    ]
